{% set name = "citeproc-ruby" %}
{% set version = "1.1.13" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 36d21003fccc3f4c608fd13e9d9fcb8cceab598f454459ab58b7bc63c692bc71

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-citeproc >=1.0.9,<=2
    - rb-csl >=1.5,<2

test:
  commands:
    - ruby -r {{ name|replace('-','/') }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ name }}-{{ version }}/BSDL
  summary: CiteProc-Ruby is a Citation Style Language (CSL) 1.0.1 compatible cite processor implementation written in pure Ruby.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/inukshuk/{{ name }}

extra:
  recipe-maintainers:
    - sodre
