travis:
  secure:
    BINSTAR_TOKEN: rx64OSdDhvnJ6JFe7Rl4bWN65T6gsa4xMRWzDDy+fsdBTXQG4GX/WhAHu4HebSi2Mg2mODPEq1fC0fpKKSmfgKlSpe1MmZVgy7B7gJyWShKO1H31LQt4DNJUpdaD0dc8vouVLNgB9o1g/0NNrpKHaFjEK7H3YntskquDHdwlYyKUjUK0eZBrUgfstJOQCrcpLtl0h53437EWto0QKGD52Ym3ufN7oxMZrfiiow8mNdQC38Z9xU2vuk7QjMneLPsQ+iFrsNB0wwIeVO/buGS/1iY1ngkErKsOQaGkZg4J1jaj7AQpLTZKZkN91XRzmrrCv/mG1XrnGuMz8NRdIUy02CTsvfFyp2DnLEZKKEaB5zL1GewLUNNWOPIpgiCixcDzD9Pc9oSxt+5cZY+pgwtLIXllPgg7JSNnRl5NgnwElFUKxj3qLE/CZP8qJfGZg/SMU3lbN9Hc6J4F+1dKyns0DeC3pQt5CAMVwhHDCJ4vjh1cveOKf5WXjoRFHhQ7TTeXmDBIvaJ9nupRsPuQ9+rKpOD/T3m1wECBoFNNLAqnji1wMU5h63JfLFOm//xKVvsy9yO8ukQW4BZz952S6ooBJbvqP1s7P4GFFrLyqcP+T5Ei9EulFMw4ONSFnX6blvbF2eAT3b4gJB2vVqreMnz3u4PBYKrUrVa/uDr4WZdcZyM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
